command: [
  "streamlit", 
  "run",
  "app.py",
  "--theme.primaryColor=#6b7280"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "STREAMLIT_THEME_BASE"
    value: "light"
