command: [
  "streamlit", 
  "run",
  "app.py",
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "STREAMLIT_THEME_BASE"
    value: "light"
  # Must be STREAMLIT_THEME_PRIMARY_COLOR (underscore), not PRIMARYCOLOR
  - name: "STREAMLIT_THEME_PRIMARY_COLOR"
    value: "#9ca3af"
